name: bag-of-rationals
dependencies:
  - python=3.8
  - pip
  - pip:
        - rational_activations==0.2.1
        - faiss_gpu==1.7.2
        - fast_pytorch_kmeans==0.1.9
        - matplotlib==3.7.1
        - pytorch_lightning==2.0.2
        - numpy==1.24.2
        - torch_geometric==2.3.0
        - torch==2.0.0
        - torchvision==0.15.1
        - scikit-learn==1.1.2
        - tensorboard-plugin-customizable-plots
        - matplotlib
        - pandas
        - coverage
        - scipy
        - pylint
        - pep8
        - pyspellchecker
        - sphinx
        - black
        - isort
        - dill
        - setuptools==65.6.3
